# Generated by Django 5.1.7 on 2025-03-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0003_alter_user_managers_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
